// Copyright (c) 2026 Danylo Fitel

// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1710:Identifiers should have correct suffix", Justification = "Priority queue interface.", Scope = "type", Target = "~T:LibSharp.Collections.IPriorityQueue`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1710:Identifiers should have correct suffix", Justification = "Max priority queue implementation.", Scope = "type", Target = "~T:LibSharp.Collections.MaxPriorityQueue`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1710:Identifiers should have correct suffix", Justification = "Min priority queue implementation.", Scope = "type", Target = "~T:LibSharp.Collections.MinPriorityQueue`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1711:Identifiers should not have incorrect suffix", Justification = "Priority queue naming is intentional and part of the public API.", Scope = "type", Target = "~T:LibSharp.Collections.IPriorityQueue`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1711:Identifiers should not have incorrect suffix", Justification = "Max priority queue naming is intentional and part of the public API.", Scope = "type", Target = "~T:LibSharp.Collections.MaxPriorityQueue`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1711:Identifiers should not have incorrect suffix", Justification = "Min priority queue naming is intentional and part of the public API.", Scope = "type", Target = "~T:LibSharp.Collections.MinPriorityQueue`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1716:Identifiers should not match keywords", Justification = "Optional<T> is the established public API name for the option-like container.", Scope = "type", Target = "~T:LibSharp.Common.Optional`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1000:Do not declare static members on generic types", Justification = "Ok/Fail factory methods are the intended construction API for Result<T, TError>.", Scope = "type", Target = "~T:LibSharp.Common.Result`2")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1000:Do not declare static members on generic types", Justification = "Empty is the named form of the default value and belongs on the type it produces, matching Result<T, TError>.Ok/Fail.", Scope = "type", Target = "~T:LibSharp.Common.Optional`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "The token sources are deliberately owned by the work rather than by this call. Work that outlives the timeout still holds the linked token, so releasing the sources when the caller stops waiting would make token.WaitHandle throw. Release disposes both once the work finishes, which the analyzer cannot see.", Scope = "member", Target = "~M:LibSharp.Common.FuncExtensions.RunWithTimeout(System.Func{System.Threading.CancellationToken,System.Threading.Tasks.Task},System.TimeSpan,System.TimeProvider,System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "The token sources are deliberately owned by the work rather than by this call. Work that outlives the timeout still holds the linked token, so releasing the sources when the caller stops waiting would make token.WaitHandle throw. Release disposes both once the work finishes, which the analyzer cannot see.", Scope = "member", Target = "~M:LibSharp.Common.FuncExtensions.RunWithTimeout``1(System.Func{System.Threading.CancellationToken,System.Threading.Tasks.Task{``0}},System.TimeSpan,System.TimeProvider,System.Threading.CancellationToken)~System.Threading.Tasks.Task{``0}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2213:Disposable fields should be disposed", Justification = "SemaphoreSlim.Dispose is not safe to call concurrently with WaitAsync, and this class never allocates the semaphore's wait handle, so it holds no unmanaged resource and garbage collection is sufficient. Disposing it would introduce a race for no benefit.", Scope = "member", Target = "~F:LibSharp.Threading.AsyncLock._semaphore")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2213:Disposable fields should be disposed", Justification = "Dispose is synchronous and cannot drain a refresh that is still running, and the value factory holds this source's token. Disposing it out from under a factory that then calls Register would throw from inside state this library handed it. A source that never had CancelAfter called holds no timer and no unmanaged handle.", Scope = "member", Target = "~F:LibSharp.Caching.ValueCacheAsync`1._cts")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA1849:Call async methods when in an async method", Justification = "Guarded by IsCompletedSuccessfully, so reading Result cannot block. Awaiting instead would turn a synchronous stale-read hit into a state machine.", Scope = "member", Target = "~M:LibSharp.Caching.ProactiveAsyncCache`1.FetchValueAsync(LibSharp.Caching.ProactiveAsyncCache{`0}.CacheSnapshot,System.Threading.CancellationToken)~System.Threading.Tasks.ValueTask{`0}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA5394:Do not use insecure randomness", Justification = "A general-purpose shuffle, not a security primitive. The XML documentation says so and points callers at a cryptographic generator when unpredictability matters.", Scope = "member", Target = "~M:LibSharp.Collections.EnumerableExtensions.Shuffle``1(System.Collections.Generic.IEnumerable{``0})~``0[]")]
